# Configuração do Checkov para Ambiente de Desenvolvimento
# Foco em verificações críticas de segurança

framework:
  - terraform

directory:
  - .
  - modules/

check:
  # Security Groups - Crítico para segurança
  - CKV_AWS_23  # Security Group permite tráfego de qualquer IP
  - CKV_AWS_24  # Security Group permite tráfego de qualquer porta
  - CKV_AWS_25  # Security Group permite tráfego ICMP
  - CKV_AWS_26  # Security Group permite tráfego SSH de qualquer IP
  - CKV_AWS_27  # Security Group permite tráfego RDP de qualquer IP
  
  # EKS Clusters - Configurações essenciais
  - CKV_AWS_37  # EKS sem logging habilitado
  - CKV_AWS_38  # EKS sem criptografia de secrets
  - CKV_AWS_39  # EKS sem configuração de endpoint privado
  - CKV_AWS_40  # EKS sem configuração de endpoint público
  
  # IAM - Políticas de acesso
  - CKV_AWS_273 # IAM role sem política de acesso mínimo
  - CKV_AWS_274 # IAM user sem política de acesso mínimo
  - CKV_AWS_275 # IAM policy permite ação "*"
  
  # KMS - Criptografia
  - CKV_AWS_43  # KMS key sem rotação automática
  - CKV_AWS_44  # KMS key sem política de acesso

# Verificações para ignorar em desenvolvimento
skip-check:
  - CKV_AWS_130 # VPC flow logs (não crítico para dev)
  - CKV_AWS_131 # VPC sem DNS habilitado (configurado manualmente)
  - CKV_AWS_132 # VPC sem DHCP habilitado (não necessário)
  - CKV_AWS_18  # S3 bucket sem versionamento (se não usar S3)
  - CKV_AWS_19  # S3 bucket sem criptografia (se não usar S3)
  - CKV_AWS_20  # S3 bucket sem logging (se não usar S3)
  - CKV_AWS_21  # S3 bucket com acesso público (se não usar S3)
  - CKV_AWS_22  # S3 bucket sem configuração de lifecycle (se não usar S3)

# Falhar apenas em problemas HIGH e CRITICAL
soft-fail-on: HIGH

# Output format
output: cli

# Arquivos para ignorar
skip-path:
  - .terraform/
  - .git/
  - node_modules/
  - .checkov/
  - terraform.tfstate*
  - *.backup

# Configurações para desenvolvimento
compact: false
quiet: false
verbose: false 