#!/bin/bash

# Script de ajuda para mostrar como usar todos os scripts
# Uso: ./scripts/help.sh

echo "🚀 SCRIPTS DE AUTOMAÇÃO EKS + ROUTE53"
echo "======================================"
echo ""
echo "📋 Todos os scripts aceitam parâmetros via linha de comando com valores padrão"
echo ""

echo "🔗 CONECTAR AO CLUSTER"
echo "======================"
echo "Uso: ./scripts/connect-to-cluster.sh [CLUSTER_NAME] [AWS_REGION] [AWS_PROFILE]"
echo "Exemplo: ./scripts/connect-to-cluster.sh my-eks-cluster us-east-1 default"
echo "Padrão: ./scripts/connect-to-cluster.sh"
echo "   → CLUSTER_NAME=my-eks-cluster"
echo "   → AWS_REGION=us-east-1"
echo "   → AWS_PROFILE=default"
echo ""

echo "🔍 VALIDAR INGRESS CONTROLLER"
echo "============================="
echo "Uso: ./scripts/validate-ingress.sh [NAMESPACE] [SERVICE_NAME] [TIMEOUT]"
echo "Exemplo: ./scripts/validate-ingress.sh ingress-nginx nginx-ingress-ingress-nginx-controller 300"
echo "Padrão: ./scripts/validate-ingress.sh"
echo "   → NAMESPACE=ingress-nginx"
echo "   → SERVICE_NAME=nginx-ingress-ingress-nginx-controller"
echo "   → TIMEOUT=300"
echo ""

echo "🧪 TESTE RÁPIDO DO INGRESS"
echo "=========================="
echo "Uso: ./scripts/test-ingress.sh [NAMESPACE] [SERVICE_NAME] [TIMEOUT]"
echo "Exemplo: ./scripts/test-ingress.sh ingress-nginx nginx-ingress-ingress-nginx-controller 60"
echo "Padrão: ./scripts/test-ingress.sh"
echo "   → NAMESPACE=ingress-nginx"
echo "   → SERVICE_NAME=nginx-ingress-ingress-nginx-controller"
echo "   → TIMEOUT=60"
echo ""

echo "🌐 CONFIGURAR ROUTE53 (COMPLETO)"
echo "==============================="
echo "Uso: ./scripts/setup-route53.sh [DOMAIN_NAME] [CLUSTER_NAME] [AWS_REGION] [AWS_PROFILE]"
echo "Exemplo: ./scripts/setup-route53.sh name.com my-eks-cluster us-east-1 default"
echo "Padrão: ./scripts/setup-route53.sh"
echo "   → DOMAIN_NAME=name.com"
echo "   → CLUSTER_NAME=my-eks-cluster"
echo "   → AWS_REGION=us-east-1"
echo "   → AWS_PROFILE=default"
echo ""

echo "🌐 APLICAR CONFIGURAÇÃO ROUTE53"
echo "=============================="
echo "Uso: ./scripts/apply-route53.sh [DOMAIN_NAME] [AWS_REGION] [AWS_PROFILE]"
echo "Exemplo: ./scripts/apply-route53.sh name.com us-east-1 default"
echo "Padrão: ./scripts/apply-route53.sh"
echo "   → DOMAIN_NAME=name.com"
echo "   → AWS_REGION=us-east-1"
echo "   → AWS_PROFILE=default"
echo ""

echo "🌐 TESTAR CONFIGURAÇÃO ROUTE53"
echo "============================="
echo "Uso: ./scripts/test-route53.sh [DOMAIN_NAME] [AWS_REGION] [AWS_PROFILE]"
echo "Exemplo: ./scripts/test-route53.sh name.com us-east-1 default"
echo "Padrão: ./scripts/test-route53.sh"
echo "   → DOMAIN_NAME=name.com"
echo "   → AWS_REGION=us-east-1"
echo "   → AWS_PROFILE=default"
echo ""

echo "📋 FLUXO RECOMENDADO"
echo "===================="
echo "1. Conectar ao cluster:"
echo "   ./scripts/connect-to-cluster.sh"
echo ""
echo "2. Validar o ingress:"
echo "   ./scripts/validate-ingress.sh"
echo ""
echo "3. Configurar Route53:"
echo "   ./scripts/apply-route53.sh"
echo ""
echo "4. Testar configuração:"
echo "   ./scripts/test-route53.sh"
echo ""

echo "🔧 EXEMPLOS DE USO COM PARÂMETROS"
echo "================================="
echo "# Usar cluster diferente:"
echo "./scripts/connect-to-cluster.sh meu-cluster-prod us-west-2 admin-prod"
echo ""
echo "# Usar domínio diferente:"
echo "./scripts/apply-route53.sh meudominio.com us-east-1 default"
echo ""
echo "# Usar timeout maior para ingress:"
echo "./scripts/validate-ingress.sh ingress-nginx nginx-ingress-ingress-nginx-controller 600"
echo ""

echo "📝 NOTAS IMPORTANTES"
echo "===================="
echo "• Todos os scripts têm valores padrão sensatos"
echo "• Parâmetros são opcionais e podem ser omitidos"
echo "• Use aspas se os valores contiverem espaços"
echo "• Certifique-se de que o kubectl está configurado"
echo "• Certifique-se de que o AWS CLI está configurado"
echo ""
echo "❓ Para mais ajuda, execute: ./scripts/help.sh" 